<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAkrxyth\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAkrxyth/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAkrxyth.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAkrxyth\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAkrxyth\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Akrxyth',
    'container.build_id' => 'f235fdea',
    'container.build_time' => 1570127415,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAkrxyth');
